### ISSUE TITLE
ValueError: Unrecognized compression type: infer

### ISSUE THREAD

**Issue by Enorya** [BBaloglu/ASHURE#3]
Hi,

I'm trying to use Ashure and I first wanted to test it on the example dataset. I've used the following command:
`ashure -spoa ../.local/bin/spoa/ run -fq external/data/COI/* -p demo/primers.csv -o1 demo/cons.csv`
At first, it seems to work well but I end up with the following error:
```
pid[62945] 2022-04-05 11:58:47.883 INFO: fwd and rev primers found
pid[62945] 2022-04-05 11:58:47.895 INFO: filtering to best aligned fragments
pid[62945] 2022-04-05 11:58:47.965 INFO: Cleaned out 0 of 16952
pid[62945] 2022-04-05 11:58:47.965 INFO: finding best primer match for each read
/home/ecol2/miniconda3/lib/python3.6/site-packages/pandas/core/indexing.py:362: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)
/home/ecol2/miniconda3/lib/python3.6/site-packages/pandas/core/indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/home/ecol2/.local/bin/ashure:445: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  df = pd.concat(tmp)
pid[62945] 2022-04-05 11:58:49.894 INFO: 5442/5601 reads with fwd and rev primer
pid[62945] 2022-04-05 11:58:49.894 INFO: 81/5601 reads with only fwd primer found
pid[62945] 2022-04-05 11:58:49.894 INFO: 78/5601 reads with only rev primer found
pid[62945] 2022-04-05 11:58:49.894 INFO: 0/5601 reads with no primer matches
pid[62945] 2022-04-05 11:58:50.139 INFO: Reference sequences found 5442
Traceback (most recent call last):
  File "/home/ecol2/.local/bin/ashure", line 1169, in <module>
    main()
  File "/home/ecol2/.local/bin/ashure", line 1064, in main
    ref.to_csv(config['db_file'], index=False, compression='infer')
  File "/home/ecol2/miniconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 1745, in to_csv
    formatter.save()
  File "/home/ecol2/miniconda3/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 156, in save
    compression=self.compression)
  File "/home/ecol2/miniconda3/lib/python3.6/site-packages/pandas/io/common.py", line 390, in _get_handle
    raise ValueError(msg)
ValueError: Unrecognized compression type: infer
```
Do you have any idea what could cause this issue? It seems linked with pandas package.

**Comment by BarbaraMpalazon** [comment]
Hi, 

Im sorry for the disturbing, but... do you have still the demo data for using as example?

Thank you in advance
